// 500 frases diarias — motivacionales, graciosas, diversas (5–8 palabras)
export const PHRASES = [
  // Amor y pareja
  "Juntos somos más raros y más felices.",
  "El amor verdadero también necesita Wi-Fi.",
  "Contigo hasta el fin del supermercado.",
  "Eres mi persona favorita en el mundo.",
  "Juntos convertimos lo ordinario en extraordinario.",
  "Mi mejor plan siempre incluye tu nombre.",
  "Contigo el caos se vuelve aventura.",
  "Eres el hogar que siempre busqué.",
  "Juntos somos imparables y un poco locos.",
  "Tu risa es mi canción favorita.",
  "Contigo cada día tiene mejor sabor.",
  "Somos el equipo que nadie vio venir.",
  "El amor crece cuando lo regas a diario.",
  "Eres raro perfecto para mi rareza perfecta.",
  "Juntos hacemos que lo difícil valga la pena.",
  "Mi corazón siempre encuentra el camino a ti.",
  "Contigo hasta los lunes son soportables.",
  "Eres el caos bonito de mi vida.",
  "Juntos escribimos la historia más bonita.",
  "Tu presencia hace que todo tenga sentido.",
  // Motivación general
  "Hoy es un buen día para ser feliz.",
  "Un pequeño paso cambia todo el panorama.",
  "Empieza y el cómo aparecerá solo.",
  "El progreso siempre supera a la perfección.",
  "Eres más valiente de lo que crees.",
  "Cada día es una nueva oportunidad brillante.",
  "Lo que buscas también te está buscando.",
  "El éxito es la suma de pequeños esfuerzos.",
  "Hoy mejor que ayer, mañana mejor que hoy.",
  "Tu energía determina tu realidad diaria.",
  "Elige crecer aunque duela un poco.",
  "El movimiento crea la motivación, no al revés.",
  "Confía en el proceso aunque no se vea.",
  "Cada esfuerzo deja una marca invisible.",
  "Lo mejor está justo después del miedo.",
  "Avanza aunque no veas toda la escalera.",
  "Tu actitud es tu superpoder más grande.",
  "Haz hoy lo que tu futuro agradecerá.",
  "La disciplina es la forma más alta de amor propio.",
  "Pequeños hábitos construyen vidas extraordinarias.",
  // Humor cotidiano
  "El café lo inventó alguien con mucha motivación.",
  "Dormir bien es el plan perfecto.",
  "El sofá me llama, pero yo resisto.",
  "Hoy me supero a mí mismo de ayer.",
  "Ser adulto nadie lo pidió pero aquí estamos.",
  "La pizza une más que ningún discurso.",
  "Hoy dije sí a la vida y al pan.",
  "El universo conspira, yo solo necesito café.",
  "Mis sueños son grandes, mi almohada también.",
  "Productividad: hacer cosas antes de mirar el teléfono.",
  "El lunes llegó sin avisar, como siempre.",
  "Mis tareas no se hacen solas, qué pena.",
  "La pereza también es una forma de soñar.",
  "Hoy me visto para triunfar o por lo menos salir.",
  "El descanso también es parte del plan.",
  "Decidí ser feliz, es más conveniente.",
  "Mi plan de hoy: sobrevivir con elegancia.",
  "El universo me da señales, yo las ignoro.",
  "Hay días de volar y días de caminar.",
  "El error de hoy es la sabiduría de mañana.",
  // Crecimiento personal
  "Aprende algo nuevo cada día sin falta.",
  "La curiosidad abre puertas que el miedo cierra.",
  "Crecer duele pero vale completamente la pena.",
  "Tu versión del año pasado te admiraría.",
  "Elige las batallas que valen tu energía.",
  "La paciencia es la madre de todas las virtudes.",
  "Conocerte es el viaje más largo e importante.",
  "El cambio empieza cuando decides que sí.",
  "Cada libro leído es un mundo ganado.",
  "La incomodidad es señal de que estás creciendo.",
  "Tu mente es el jardín más importante.",
  "Celebra los avances aunque sean pequeños.",
  "La gratitud transforma lo ordinario en suficiente.",
  "Ser honesto contigo mismo es el primer paso.",
  "Los límites que pones te definen y liberan.",
  "Aprende del pasado sin vivir en él.",
  "El descanso activo también es productividad real.",
  "Tu intuición rara vez se equivoca del todo.",
  "Las conversaciones difíciles limpian el aire.",
  "Pide ayuda: los héroes también tienen equipo.",
  // Naturaleza y calma
  "Respira profundo, el universo puede esperar.",
  "La calma es la clave de todo lo demás.",
  "Un paseo cambia más que mil pensamientos.",
  "La naturaleza siempre tiene la respuesta correcta.",
  "El sol sale todos los días sin fallar.",
  "Las plantas crecen lento y llegan lejos.",
  "El mar no tiene prisa y llega lejos.",
  "En silencio también se escucha la vida.",
  "La lluvia lava lo que el sol no puede.",
  "Cada amanecer borra lo que ayer no funcionó.",
  "El viento no sabe de imposibles ni dudas.",
  "Florece despacio pero florece con fuerza.",
  "La tierra siempre devuelve lo que recibe.",
  "Las estrellas brillan más cuando hay oscuridad.",
  "El río no se disculpa por fluir.",
  "Las montañas no se mueven, se escalan.",
  "Un árbol fuerte tiene raíces profundas invisibles.",
  "El cielo de hoy nunca existirá igual.",
  "La naturaleza nos recuerda lo que importa.",
  "Sé como el bambú: flexible pero sin romperse.",
  // Filosofía ligera
  "La vida es demasiado corta para el drama.",
  "El tiempo es el único recurso que no vuelve.",
  "Sé la energía que deseas encontrar en otros.",
  "Lo simple suele ser lo más verdaderamente profundo.",
  "No hay camino correcto, solo el que eliges.",
  "El destino lo construyes con decisiones diarias.",
  "Todo pasa, y eso incluye lo malo.",
  "La felicidad no se espera, se practica.",
  "Vivir bien es la mejor forma de brillar.",
  "El presente es el único lugar real.",
  "Lo que piensas crea lo que vives.",
  "Confía en que todo tiene su tiempo.",
  "Las mejores cosas vienen cuando las sueltas.",
  "El miedo avisa pero no debe decidir.",
  "Una mente abierta encuentra puertas en paredes.",
  "La vida no te da lo que mereces, lo que decides.",
  "Sé curioso, las respuestas llegan solos.",
  "El equilibrio es arte, no ciencia exacta.",
  "Nadie tiene la respuesta perfecta, solo su verdad.",
  "El significado lo pones tú, no el universo.",
  // Productividad con humor
  "La lista de tareas: enemiga y mejor amiga.",
  "Hice una cosa hoy y me siento campeón.",
  "El multitasking es el mito del siglo.",
  "Enfocarse en una cosa es poder real.",
  "El pendiente de ayer hoy puede ser fiesta.",
  "Tachan una tarea: satisfacción nivel máximo.",
  "El orden exterior refleja el interior siempre.",
  "Priorizar es decir no con mucha gracia.",
  "Las distracciones también necesitan su propio límite.",
  "Hoy me comprometí con una sola cosa.",
  "El silencio del teléfono es el sonido del éxito.",
  "Planear bien es trabajar menos, no más.",
  "Una cosa hecha supera diez cosas pensadas.",
  "El inicio es siempre la parte más difícil.",
  "Termina lo que empezaste, aunque cueste trabajo.",
  "La energía matutina es el oro del día.",
  "Desconectar a tiempo también es productividad real.",
  "Un objetivo claro vale más que cien planes.",
  "Celebra cada tarea completada, en serio.",
  "La constancia gana siempre a la intensidad.",
  // Bienestar y salud
  "Tu cuerpo es tu casa más importante.",
  "Moverse es la mejor medicina disponible hoy.",
  "El sueño es productividad oculta y necesaria.",
  "Comer bien es querer bien tu cuerpo.",
  "El agua es el reset que siempre necesitas.",
  "Cuídate como cuidarías a quien más amas.",
  "El descanso no es debilidad, es estrategia.",
  "Un cuerpo sano sostiene los grandes sueños.",
  "Respeta tus límites físicos y mentales hoy.",
  "La salud es la base de todo lo demás.",
  "Date permiso de parar cuando lo necesites.",
  "Un buen hábito cambia más que mil propósitos.",
  "El estrés crónico no es una medalla.",
  "Reír mucho es medicina económica y efectiva.",
  "Escucha lo que tu cuerpo intenta decirte.",
  "La hidratación es el hack más subestimado.",
  "Salir a caminar resuelve más de lo que crees.",
  "Tu salud mental importa tanto como la física.",
  "Pedir ayuda es fortaleza, no debilidad.",
  "Un día a la vez, sin más carga.",
  // Amistad y conexión
  "Las buenas conversaciones nutren el alma.",
  "Un amigo de verdad vale más que oro.",
  "La conexión humana es el mayor lujo.",
  "Llama a alguien hoy sin motivo especial.",
  "Las personas correctas aparecen en el momento justo.",
  "La risa compartida es el mejor vínculo.",
  "Rodéate de quienes te hacen mejor persona.",
  "Un mensaje a tiempo puede cambiar un día.",
  "Las relaciones se riegan con presencia real.",
  "La empatía es el idioma universal que une.",
  "Escuchar de verdad es el regalo más raro.",
  "Las mejores amistades sobreviven al silencio.",
  "La generosidad siempre regresa multiplicada.",
  "Un abrazo resuelve cosas que las palabras no.",
  "La tribu correcta te hace invencible.",
  "Celebra los logros de los demás con generosidad.",
  "Las personas que te quieren te dicen la verdad.",
  "La distancia no apaga los vínculos reales.",
  "Comparte lo bueno, el gozo crece al hacerlo.",
  "El tiempo con las personas correctas es sagrado.",
  // Creatividad
  "Las mejores ideas llegan en la ducha.",
  "Crear es la forma más humana de existir.",
  "El arte no necesita permiso para nacer.",
  "Crea sin miedo al juicio ajeno hoy.",
  "La creatividad florece donde hay espacio libre.",
  "Equivocarse es parte del proceso creativo siempre.",
  "Haz algo con las manos hoy, lo que sea.",
  "Las ideas sin acción son solo sueños bonitos.",
  "La imaginación no tiene límites ni horario.",
  "Crea hoy algo que mañana te sorprenda.",
  "El color de tu vida lo eliges tú.",
  "Jugar en serio es la forma más seria.",
  "La música cambia el estado de ánimo siempre.",
  "Escribe aunque solo lo leas tú después.",
  "El aburrimiento es el padre de las ideas.",
  "Una idea descabellada puede ser la mejor.",
  "Crear es resistir, y resistir es sobrevivir.",
  "La originalidad es atreverse a ser uno mismo.",
  "Las mejores historias las vives, no las ves.",
  "Improvisa más, planifiques menos algunas veces.",
  // Humor absurdo
  "Los lunes existen para valorar los viernes.",
  "El aguacate no me fallará hoy tampoco.",
  "Sobreviví otra reunión que era un email.",
  "Mi planta sigue viva, soy responsable.",
  "El orden de los factores altera el desayuno.",
  "Declaro hoy oficialmente un buen día.",
  "El misterio de los calcetines perdidos persiste.",
  "Hoy no procrastino, mañana sí quizás.",
  "El queso lo resuelve casi todo.",
  "Mis metas son grandes, mis siestas también.",
  "La vida da vueltas, agárrate bien fuerte.",
  "El sol salió para todos, inclúyete.",
  "Mi motivación llegó tarde pero llegó firme.",
  "El universo habla, yo tengo auriculares.",
  "Plan perfecto: que salga bien lo planeado.",
  "El invierno pasará, el verano siempre vuelve.",
  "Funciono mejor con música y buena energía.",
  "Mi nivel de adulto hoy: aceptable.",
  "La vida es bella, especialmente con café.",
  "El tráfico también tiene su filosofía propia.",
  // Gratitud
  "Agradecer lo pequeño multiplica lo grande.",
  "La gratitud es el idioma de los sabios.",
  "Hoy hay más cosas buenas que malas.",
  "Agradece el presente antes de pedir más.",
  "Lo que tienes hoy fue el sueño de ayer.",
  "La abundancia empieza por ver lo suficiente.",
  "Cada día tiene al menos una razón.",
  "Ser agradecido es el primer paso hacia la paz.",
  "La gratitud silencia la queja más poderosa.",
  "Celebra lo ordinario, que no es tan ordinario.",
  "Agradecer en voz alta transforma el ambiente.",
  "Lo bueno de hoy no necesita ser enorme.",
  "Hay belleza en lo cotidiano si la buscas.",
  "La gratitud no cuesta nada y lo cambia todo.",
  "Hoy agradezco lo que ayer di por sentado.",
  "Mirar atrás solo para ver cuánto avanzaste.",
  "El lujo más real es la paz interior.",
  "Agradece antes de dormir, mejora el sueño.",
  "La vida perfecta no existe, la buena sí.",
  "Gracias por hoy, aunque haya sido difícil.",
  // Desafíos y resiliencia
  "Las cicatrices cuentan historias de sobrevivencia.",
  "Lo que no te destruye te transforma completamente.",
  "Caer no es fracasar, quedarse sí.",
  "El obstáculo es también la ruta a veces.",
  "La tormenta siempre precede a la calma.",
  "Las crisis revelan lo que el sol oculta.",
  "Resiste un poco más, el giro viene.",
  "La adversidad construye lo que la comodidad no.",
  "Eres más fuerte que cualquier mal día.",
  "El fracaso es datos, no diagnóstico final.",
  "Después de cada no viene el sí correcto.",
  "Las pruebas más duras forjan el carácter.",
  "Perder es aprender a un costo más alto.",
  "Lo que parece el fin es solo un giro.",
  "La resiliencia no se nace, se entrena.",
  "Levantarse es la habilidad más importante.",
  "El caos tiene orden si miras con calma.",
  "La paciencia vence lo que la fuerza no.",
  "Los mejores capítulos vienen después del conflicto.",
  "Sigue, siempre hay algo por lo que seguir.",
  // Éxito y logros
  "El éxito tiene muchas formas distintas.",
  "Los grandes logros empiezan con decisiones pequeñas.",
  "Celebra cada victoria aunque nadie la vea.",
  "El camino al éxito está lleno de curvas.",
  "Define tu propio éxito antes de perseguirlo.",
  "Los logros silenciosos también merecen fiesta.",
  "El talento sin esfuerzo duerme sin despertar.",
  "Constancia más paciencia igual a resultados reales.",
  "El éxito de otro no quita el tuyo.",
  "Tu timeline de logros es solo tuyo.",
  "Nadie llega al éxito en línea recta.",
  "El trabajo duro no miente a largo plazo.",
  "Rodéate de quienes ya están donde quieres.",
  "Las metas grandes se comen en bocados pequeños.",
  "La claridad de propósito acelera cualquier camino.",
  "Aprender de los mejores es ventaja estratégica.",
  "El primer éxito abre la mente a más.",
  "Comprométete con el proceso, los resultados llegan.",
  "El nivel de exigencia propio determina los logros.",
  "Cada sueño cumplido fue primero una decisión.",
  // Tiempo libre y disfrute
  "El placer sin culpa también es salud.",
  "Jugar no es para niños, es para humanos.",
  "La música es el reset más rápido.",
  "Un buen libro es vacaciones para la mente.",
  "El ocio creativo no existe, es todo creativo.",
  "Disfrutar el presente no es irresponsabilidad.",
  "Las vacaciones mentales también son necesarias.",
  "Ríete fuerte aunque no venga al caso.",
  "El placer de lo simple es el más profundo.",
  "Date permiso de disfrutar sin explicaciones.",
  "Bailar aunque nadie te vea es libertad.",
  "Una tarde libre recarga lo que nada más puede.",
  "El juego es la forma más seria de aprender.",
  "La risa diaria es medicina preventiva real.",
  "Disfruta el camino, no solo el destino.",
  "Un hobby te recuerda quién eres sin presión.",
  "Explorar sin mapa es descubrir más cosas.",
  "La aventura empieza justo donde termina la rutina.",
  "Celebrar lo pequeño hace la vida más grande.",
  "Permítete estar bien sin motivo aparente.",
  // Finanzas y propósito (ligero)
  "Ahorra hoy para celebrar tranquilo mañana.",
  "El dinero es herramienta, no el objetivo.",
  "Invertir en ti siempre da buenos retornos.",
  "Gastar en experiencias vale más que cosas.",
  "La claridad financiera da paz y libertad.",
  "El propósito claro da energía sin límites.",
  "Haz lo que amas y el resto acompaña.",
  "El trabajo con sentido no se siente trabajo.",
  "Tu tiempo es tu moneda más valiosa.",
  "Lo que aportas al mundo regresa multiplicado.",
  "Invierte en relaciones más que en objetos.",
  "El ahorro es libertad en versión lenta.",
  "Gana bien, gasta mejor, da más.",
  "Trabaja con intención, no solo con esfuerzo.",
  "El propósito da energía que el sueldo no.",
  "La generosidad siempre tiene su propio rendimiento.",
  "Construye algo que dure más que tú.",
  "El legado se hace con decisiones diarias.",
  "Invierte en lo que te hace crecer siempre.",
  "La riqueza verdadera está en el tiempo libre.",
  // Más amor y conexión de pareja
  "El equipo más poderoso del mundo somos nosotros.",
  "Cada día me alegra haberte elegido a ti.",
  "Contigo los problemas tienen mejor perspectiva.",
  "Tu sonrisa sigue siendo mi lugar favorito.",
  "Construimos algo hermoso sin darnos cuenta.",
  "Somos el proyecto más bonito que tenemos.",
  "Juntos hacemos que lo cotidiano sea especial.",
  "Mi aventura favorita es la que vivimos juntos.",
  "Contigo aprendí que el amor también se decide.",
  "Eres la persona con quien quiero crecer.",
  "El mejor acuerdo que tomé fue estar contigo.",
  "Juntos somos más que la suma de partes.",
  "Tu confianza me da alas que no sabía tener.",
  "Contigo hasta los planes fallidos son bonitos.",
  "Compartir la vida contigo es el regalo.",
  "Tu risa es el mejor sonido que conozco.",
  "Hacemos un equipo ridículo y perfecto.",
  "Eres mi favorito en todos los idiomas.",
  "Contigo el hogar es donde estemos nosotros.",
  "Gracias por elegirme cada día de nuevo.",
  // Motivación extra
  "Hoy tienes todo lo necesario para empezar.",
  "La versión que serás te está esperando.",
  "Un paso hacia adelante cuenta siempre.",
  "Decides todos los días quién quieres ser.",
  "El momento perfecto es ahora, no después.",
  "No esperes estar listo para comenzar ya.",
  "Tu historia aún no ha llegado a lo mejor.",
  "Eres la suma de tus decisiones diarias.",
  "Lo que haces hoy importa más de lo crees.",
  "El coraje es actuar aunque el miedo esté.",
  "Tu potencial supera tus peores pensamientos.",
  "La perseverancia siempre tiene la última palabra.",
  "Cada mañana es una página en blanco nueva.",
  "Transforma la intención en acción concreta hoy.",
  "El mejor proyecto eres tú mismo siempre.",
  "Eres más capaz de lo que piensas.",
  "Haz una cosa que te acerque a tu meta.",
  "La versión de mañana la construyes hoy.",
  "Confía en ti mismo aunque no todo esté claro.",
  "El éxito silencioso también es éxito real.",
];
